package com.scriptflow.export.service;

import com.scriptflow.common.exception.BusinessException;
import com.scriptflow.common.result.ResultCode;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.poi.xwpf.usermodel.ParagraphAlignment;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;

/**
 * Multi-format export service.
 * Supports PDF (PDFBox), Word/ DOCX (Apache POI), and FDX (Fountain plaintext).
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ExportService {

    /**
     * Export script content to the specified format.
     *
     * @param scriptId    script ID
     * @param yamlContent the YAML script content
     * @param format      export format: pdf, docx, fdx
     * @return byte array of the exported file
     */
    public byte[] export(Long scriptId, String yamlContent, String format) {
        return switch (format.toLowerCase()) {
            case "pdf" -> exportToPdf(scriptId, yamlContent);
            case "docx" -> exportToDocx(scriptId, yamlContent);
            case "fdx" -> exportToFdx(scriptId, yamlContent);
            default -> throw new BusinessException(ResultCode.PARAM_ERROR, "Unsupported format: " + format);
        };
    }

    /**
     * PDF export using Apache PDFBox.
     * Creates a paginated document with the YAML content in monospace font.
     */
    private byte[] exportToPdf(Long scriptId, String yamlContent) {
        try (PDDocument doc = new PDDocument();
             ByteArrayOutputStream baos = new ByteArrayOutputStream()) {

            String[] lines = yamlContent.split("\n");
            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);

            PDPageContentStream cs = new PDPageContentStream(doc, page);
            try {
                PDType1Font courier = new PDType1Font(Standard14Fonts.FontName.COURIER);
                PDType1Font helveticaBold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                PDType1Font helvetica = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

                cs.setFont(courier, 8);
                cs.setLeading(12f);
                cs.beginText();
                cs.newLineAtOffset(50, 800);

                cs.setFont(helveticaBold, 14);
                cs.showText("Script Export - ID: " + scriptId);
                cs.newLine();
                cs.setFont(helvetica, 8);
                cs.showText("Generated by ScriptFlow");
                cs.newLine();
                cs.newLine();

                cs.setFont(courier, 8);
                float y = 770;
                for (String line : lines) {
                    if (y < 50) {
                        cs.endText();
                        cs.close();
                        page = new PDPage(PDRectangle.A4);
                        doc.addPage(page);
                        cs = new PDPageContentStream(doc, page);
                        cs.setFont(courier, 8);
                        cs.setLeading(12f);
                        cs.beginText();
                        cs.newLineAtOffset(50, 800);
                        y = 800;
                    }
                    String displayLine = line.length() > 100 ? line.substring(0, 100) + "..." : line;
                    cs.showText(displayLine);
                    cs.newLine();
                    y -= 12;
                }
                cs.endText();
            } finally {
                cs.close();
            }

            doc.save(baos);
            log.info("PDF export completed for script: {}, {} lines", scriptId, lines.length);
            return baos.toByteArray();
        } catch (Exception e) {
            log.error("PDF export failed for script: {}", scriptId, e);
            throw new BusinessException(ResultCode.EXPORT_ERROR, "PDF export failed: " + e.getMessage());
        }
    }

    /**
     * DOCX export using Apache POI XWPF.
     */
    private byte[] exportToDocx(Long scriptId, String yamlContent) {
        try (XWPFDocument doc = new XWPFDocument();
             ByteArrayOutputStream baos = new ByteArrayOutputStream()) {

            // Title
            XWPFParagraph title = doc.createParagraph();
            title.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun titleRun = title.createRun();
            titleRun.setText("Script Export - ID: " + scriptId);
            titleRun.setBold(true);
            titleRun.setFontSize(16);
            titleRun.setFontFamily("Arial");

            // Subtitle
            XWPFParagraph subtitle = doc.createParagraph();
            subtitle.setAlignment(ParagraphAlignment.CENTER);
            XWPFRun subRun = subtitle.createRun();
            subRun.setText("Generated by ScriptFlow");
            subRun.setFontSize(10);
            subRun.setFontFamily("Arial");
            subRun.setItalic(true);

            // Separator
            doc.createParagraph();

            // Content lines
            for (String line : yamlContent.split("\n")) {
                XWPFParagraph para = doc.createParagraph();
                XWPFRun run = para.createRun();
                run.setText(line);
                run.setFontFamily("Courier New");
                run.setFontSize(9);
                run.setColor("#333333");
            }

            doc.write(baos);
            log.info("DOCX export completed for script: {}", scriptId);
            return baos.toByteArray();
        } catch (Exception e) {
            log.error("DOCX export failed for script: {}", scriptId, e);
            throw new BusinessException(ResultCode.EXPORT_ERROR, "DOCX export failed: " + e.getMessage());
        }
    }

    /**
     * FDX (Fountain) export - generates Fountain plaintext format.
     * Fountain is a plaintext screenplay markup language.
     */
    private byte[] exportToFdx(Long scriptId, String yamlContent) {
        try {
            StringBuilder fountain = new StringBuilder();
            fountain.append("Title: Script ").append(scriptId).append("\n");
            fountain.append("Credit: Written by ScriptFlow\n");
            fountain.append("Source: Generated from novel analysis\n");
            fountain.append("Draft date: ").append(new java.text.SimpleDateFormat("yyyy-MM-dd")
                    .format(new java.util.Date())).append("\n");
            fountain.append("==================================\n\n");

            // Parse YAML-like content and convert to fountain format
            for (String line : yamlContent.split("\n")) {
                String trimmed = line.trim();
                if (trimmed.isEmpty()) {
                    fountain.append("\n");
                } else if (trimmed.startsWith("title:") || trimmed.startsWith("Title:")) {
                    fountain.append(trimmed.replaceFirst("(?i)title:", "Title:")).append("\n\n");
                } else if (trimmed.startsWith("scene:") || trimmed.startsWith("Scene:")) {
                    fountain.append("\n").append(". ").append(trimmed.replaceFirst("(?i)scene:", "")).append("\n\n");
                } else if (trimmed.startsWith("character:") || trimmed.startsWith("Character:")) {
                    fountain.append(trimmed.replaceFirst("(?i)character:", "").trim().toUpperCase()).append("\n");
                } else if (trimmed.startsWith("dialogue:") || trimmed.startsWith("Dialogue:")) {
                    fountain.append(trimmed.replaceFirst("(?i)dialogue:", "")).append("\n");
                } else if (trimmed.startsWith("action:") || trimmed.startsWith("Action:")) {
                    fountain.append(trimmed.replaceFirst("(?i)action:", "")).append("\n");
                } else {
                    fountain.append(trimmed).append("\n");
                }
            }

            log.info("FDX export completed for script: {}", scriptId);
            return fountain.toString().getBytes(StandardCharsets.UTF_8);
        } catch (Exception e) {
            log.error("FDX export failed for script: {}", scriptId, e);
            throw new BusinessException(ResultCode.EXPORT_ERROR, "FDX export failed: " + e.getMessage());
        }
    }
}
